global using BlazingPizza.BusinessObjects.Aggregates;
global using BlazingPizza.BusinessObjects.Dtos;
global using BlazingPizza.BusinessObjects.Entities;
global using BlazingPizza.BusinessObjects.Interfaces.Checkout;
global using BlazingPizza.BusinessObjects.Interfaces.Common;
global using BlazingPizza.BusinessObjects.Interfaces.ConfigurePizzaDialog;
global using BlazingPizza.BusinessObjects.Interfaces.Index;
global using BlazingPizza.BusinessObjects.Interfaces.Specials;
global using Microsoft.Extensions.DependencyInjection;
